[project]
name = "ytpmvmaker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nordbahnhof", email = "323519151+vbe-robotron@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "audioop-lts>=0.2.2",
    "flet>=1.0.0",
    "mido>=1.3.3",
    "numpy>=2.5.3",
    "pydub>=0.25.1",
]

[project.scripts]
ytpmvmaker = "ytpmvmaker:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
